name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize agent with '...'
        2. Execute action '...'
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide relevant environment information
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 14, Windows 11]
        - Python version: [e.g., 3.10.5]
        - Agent Control Plane version: [e.g., 1.1.0]
        - Installation method: [pip, git clone, docker]
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please paste any relevant log output or error messages
      render: shell
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, code snippets, etc.)
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
